# -*- coding: utf-8 -*-
"""multiple_linear_regression_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0GLyc4ILbvNGgx-9nzDqdEp6bAphqBT
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Create synthetic dataset
np.random.seed(42)
n = 50
area_sqft = np.random.randint(600, 3000, n)
num_bedrooms = np.random.randint(1, 5, n)
age_years = np.random.randint(0, 30, n)

# Price formula with noise
price_lakhs = (area_sqft * 0.05) + (num_bedrooms * 10) - (age_years * 1.5) + np.random.normal(0, 20, n)

# Build DataFrame
df = pd.DataFrame({
    "area_sqft": area_sqft,
    "num_bedrooms": num_bedrooms,
    "age_years": age_years,
    "price_lakhs": price_lakhs
})

# Features and target
X = df[["area_sqft", "num_bedrooms", "age_years"]]
y = df["price_lakhs"]

# Train regression model
model = LinearRegression()
model.fit(X, y)

print("Intercept:", model.intercept_)
print("Coefficients:", dict(zip(X.columns, model.coef_)))

# Predictions
y_pred = model.predict(X)
print("\nFirst 5 Actual vs Predicted:")
print(pd.DataFrame({"Actual": y[:5], "Predicted": y_pred[:5]}))

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))
r2 = r2_score(y, y_pred)

print("\nMAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

# Comments:
# MAE shows the average prediction error in lakhs.
# RMSE penalizes larger errors more heavily, giving a sense of spread.
# R² indicates how much variance in price is explained by the features.

import matplotlib.pyplot as plt

# Residuals
residuals = y - y_pred

# Plot histogram
plt.hist(residuals, bins=10, edgecolor="black")
plt.title("Histogram of Residuals")
plt.xlabel("Residuals (Actual - Predicted)")
plt.ylabel("Frequency")
plt.show()

# Explanation:
# A residual is the difference between actual and predicted values.
# If the histogram is roughly centered around zero and symmetric,
# it suggests the model errors are balanced and assumptions hold.