# -*- coding: utf-8 -*-
"""Reproduce_and_Identify_Leakag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sf-IUJ-HdkGvKi2fcHUWol3XxZLItGT4
"""

from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Generate synthetic dataset
X, y = make_classification(n_samples=1000, n_features=10, random_state=42)

# ❌ Flawed approach: scale before splitting
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split after scaling
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Train Logistic Regression
model = LogisticRegression()
model.fit(X_train, y_train)

print("Train Accuracy:", model.score(X_train, y_train))
print("Test Accuracy:", model.score(X_test, y_test))

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score

# Split first
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Pipeline: scaling + logistic regression
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression())
])

# Fit on training data
pipeline.fit(X_train, y_train)

print("Train Accuracy:", pipeline.score(X_train, y_train))
print("Test Accuracy:", pipeline.score(X_test, y_test))

# Cross-validation
scores = cross_val_score(pipeline, X, y, cv=5)
print("CV Mean Accuracy:", scores.mean())
print("CV Std Dev:", scores.std())

from sklearn.tree import DecisionTreeClassifier

depths = [1, 5, 20]
results = []

for d in depths:
    tree = DecisionTreeClassifier(max_depth=d, random_state=42)
    tree.fit(X_train, y_train)
    train_acc = tree.score(X_train, y_train)
    test_acc = tree.score(X_test, y_test)
    results.append((d, train_acc, test_acc))

# Print results as a table
print("Depth | Train Accuracy | Test Accuracy")
for d, tr, te in results:
    print(f"{d:<5} | {tr:.3f}          | {te:.3f}")